language: node_js

sudo: false
dist: trusty

node_js:
  - '10'

branches:
  only:
  - master

#addons:
#  apt:
#    sources:
#      - ubuntu-toolchain-r-test
#    packages:
#      - g++-4.8

before_install:
  - npm i -g npm@latest

install:
  - travis_retry npm i

before_script:

script:
  - npm run build:prod

git:
  depth: 1

deploy:
  provider: heroku
  api_key: $HEROKU_API_KEY
  app: pulse24
